show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('SAM', 'MATTHEW', 'IT', 65000);
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('FARUKH', 'AHMED', 'IT', 80000);
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('KUNAL', 'GUPTA', 'HR', 40000);
## Q1:
select substring(FIRST_NAME,1,3) as FIRST_THREE_LETTER from WORKER;
## Q2.
SELECT FIRST_NAME, POSITION('a' IN FIRST_NAME) FROM WORKER;
## Q3.
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME_OF_EMPLOYEES, DEPARTMENT, SALARY FROM WORKER
WHERE SALARY IN (SELECT MAX(SALARY) FROM WORKER GROUP BY DEPARTMENT);