show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('VIPUL', 'GROVER', 'HR', 55000, 'VIPUL GROVER');
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('ZIA', 'AHMED', 'HR', 61000, 'ZIA AHMED', '2015-04-07');
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('Amitabh', 'GUPTA', 'IT', 90000,NULL);
insert into WORKER VALUES('ABHI', 'GUPTA', 'EXAM', 90000,NULL);
## Q1:
ALTER TABLE WORKER ADD COLUMN JOINING_DATE DATE;
UPDATE WORKER SET JOINING_DATE='2018-07-15' WHERE FIRST_NAME NOT LIKE 'A%' AND FIRST_NAME NOT LIKE '_____H';
SELECT * FROM WORKER WHERE JOINING_DATE BETWEEN '2014-02-01' AND '2014-02-28';
## Q2.
SELECT *,COUNT(LAST_NAME) FROM WORKER GROUP BY LAST_NAME HAVING COUNT(LAST_NAME)>1;
## Q3.
CREATE TABLE WORKER_BKP AS SELECT DISTINCT * FROM WORKER;
DROP TABLE WORKER;
ALTER TABLE WORKER_BKP RENAME TO WORKER;
SELECT * FROM WORKER;