show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('SAM', 'MATTHEW', 'IT', 65000);
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('FARUKH', 'AHMED', 'IT', 80000);
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('KUNAL', 'GUPTA', 'HR', 40000);
## Q1:
select FIRST_NAME from WORKER;
## Q2.
SELECT DEPARTMENT FROM WORKER GROUP BY DEPARTMENT;
## Q3.
SELECT * FROM WORKER ORDER BY SALARY DESC LIMIT 5;