show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('VIPUL', 'GROVER', 'HR', 55000, 'VIPUL GROVER');
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('FARUKH', 'AHMED', 'IT', 80000);
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('Amitabh', 'GUPTA', 'IT', 90000,NULL);
insert into WORKER VALUES('ABHI', 'GUPTA', 'EXAM', 90000,NULL);
## Q1:
SELECT RIGHT(FULL_NAME,CHAR_LENGTH(FULL_NAME)-POSITION(' ' IN FULL_NAME)) FROM WORKER WHERE FIRST_NAME IN ('VIPUL', 'SATISH');
SELECT RIGHT(FULL_NAME,CHAR_LENGTH(FULL_NAME)-POSITION(' ' IN FULL_NAME)) FROM WORKER;
## Q2.
SELECT * FROM WORKER WHERE FIRST_NAME LIKE '_____H';
## Q3.
SELECT CONCAT(FIRST_NAME,LAST_NAME,'.',DEPARTMENT,'@GMAIL.COM') AS EMAILS FROM WORKER;