show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('SAM', 'MATTHEW', 'IT', 65000);
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('FARUKH', 'AHMED', 'IT', 80000);
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('KUNAL', 'GUPTA', 'HR', 40000);
## Q1:
ALTER TABLE WORKER ADD COLUMN FULL_NAME VARCHAR(40);
UPDATE WORKER SET FULL_NAME=CONCAT(FIRST_NAME,' ',LAST_NAME);
SELECT LEFT(FULL_NAME,POSITION(' ' IN FULL_NAME)) AS FIRST_NAME FROM WORKER;
## Q2.
SELECT DEPARTMENT, CHAR_LENGTH(DEPARTMENT), COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT;
## Q3.
SELECT SALARY FROM WORKER ORDER BY SALARY DESC;