show databases;
use college;
create table WORKER (FIRST_NAME VARCHAR(20), LAST_NAME VARCHAR(20), DEPARTMENT VARCHAR(20), SALARY INT(7));
SELECT * FROM WORKER;
insert into WORKER VALUES('SAM', 'MATTHEW', 'IT', 65000);
insert into WORKER VALUES('RUPALI', 'KASHYUP', 'SALES', 75000);
insert into WORKER VALUES('HARSH', 'MISHRA', 'HR', 30000);
insert into WORKER VALUES('FARUKH', 'AHMED', 'IT', 80000);
insert into WORKER VALUES('ARCHANA', 'SHARMA', 'SALES', 40000);
insert into WORKER VALUES('Amitabh', 'GUPTA', 'IT', 90000,NULL);
insert into WORKER VALUES('ABHI', 'GUPTA', 'EXAM', 90000,NULL);
## Q1:
SELECT REPLACE(FIRST_NAME,'a','A') AS NEW_FIRST_NAME FROM WORKER;
## Q2.
SELECT * FROM WORKER ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;
## Q3.
SELECT FIRST_NAME, SALARY FROM WORKER WHERE SALARY= (SELECT MAX(SALARY) FROM WORKER);